name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js, Bun, and install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
      - uses: oven-sh/setup-bun@v2
        with:
          cache: bun
      - run: bun install
      - run: bun run lint

      - name: Publish to npm and GitHub Packages
        run: |
          npm publish --access=public
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
