name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: oven-sh/setup-bun@v2
        with:
          node-version: "20"
          cache: bun
      - run: bun install
      - run: bun run lint
